// --- DATA STORE ---
        const internshipsData = [ { id: 'int01', title: 'AICTE Internship Program', provider: 'AICTE', description: 'Provides internships in various government departments and private companies through the TULIP portal.', fields: ['engineering', 'management', 'technical'], educationLevel: ['undergraduate', 'graduate'], link: 'https://internship.aicte-india.org/' }, { id: 'int02', title: 'Swachh Bharat Summer Internship', provider: 'Ministry of Jal Shakti', description: 'A 100-hour experiential internship for students to contribute to the Swachh Bharat Mission in rural areas.', fields: ['arts', 'social_work', 'management', 'engineering'], educationLevel: ['12th_pass', 'undergraduate'], link: 'https://youth.gov.in/sbsi-2019' }, { id: 'int03', title: 'NITI Aayog Internship Scheme', provider: 'NITI Aayog, Govt. of India', description: 'Engage in policy research and analysis at the premier policy think tank of the Government of India.', fields: ['arts', 'management', 'engineering', 'technical', 'medical'], educationLevel: ['undergraduate', 'graduate'], link: 'https://www.niti.gov.in/internship' }, { id: 'int04', title: 'DRDO Research Internship', provider: 'Defence Research and Development Organisation', description: 'Opportunities for students to work on cutting-edge research projects in defence technology.', fields: ['engineering', 'technical'], educationLevel: ['undergraduate', 'graduate'], link: 'https://www.drdo.gov.in/careers' }, { id: 'int05', title: 'Jammu & Kashmir High Court - Law Interns', provider: 'High Court of Jammu & Kashmir and Ladakh', description: 'An opportunity for law students to get firsthand experience of the judicial system.', fields: ['arts'], educationLevel: ['undergraduate', 'graduate'], link: 'https://jkhighcourt.nic.in/' } ];
        const scholarshipsData = [ { id: 'sch01', title: "Prime Minister's Special Scholarship Scheme (PMSSS)", provider: 'AICTE, Ministry of Education', description: 'Financial aid for J&K and Ladakh students to pursue undergraduate studies in professional colleges outside the UT.', eligibilityLevel: ['post12th'], category: ['general', 'sc_st', 'obc', 'ews', 'girls'], field: ['professional'], link: 'https://www.aicte-jk-scholarship-gov.in/' }, { id: 'sch02', title: 'Post-Matric Scholarship for ST/SC Students', provider: 'J&K Dept of Social Welfare', description: 'Financial assistance for ST/SC students for studies beyond matriculation (Class 11 to PhD).', eligibilityLevel: ['post10th', 'post12th'], category: ['sc_st'], field: ['general', 'professional'], link: 'https://scholarships.gov.in/' }, { id: 'sch03', title: 'Begum Hazrat Mahal National Scholarship', provider: 'Ministry of Minority Affairs', description: 'Scholarship for meritorious girl students belonging to the six notified minority communities.', eligibilityLevel: ['post10th'], category: ['girls'], field: ['general'], link: 'https://scholarships.gov.in/' }, { id: 'sch04', title: 'Post-Matric Scholarship for OBC/EWS Students', provider: 'J&K Dept of Social Welfare', description: 'Financial assistance for students from OBC and Economically Weaker Sections for post-matriculation studies.', eligibilityLevel: ['post10th', 'post12th'], category: ['obc', 'ews'], field: ['general', 'professional'], link: 'https://scholarships.gov.in/' } ];

        document.addEventListener('DOMContentLoaded', () => {
            // --- LOGIN LOGIC ---
            const loginBtn = document.getElementById('loginBtn');
            const profileIcon = document.getElementById('profileIcon');
            const loginModal = document.getElementById('loginModal');
            const loginModalContent = document.getElementById('loginModalContent');
            const closeLoginBtn = document.getElementById('closeLogin');
            const loginForm = document.getElementById('loginForm');
            function updateLoginUI() { if (localStorage.getItem('isLoggedIn') === 'true') { loginBtn.classList.add('hidden'); profileIcon.classList.remove('hidden'); } else { loginBtn.classList.remove('hidden'); profileIcon.classList.add('hidden'); } }
            loginBtn.addEventListener('click', () => { loginModal.classList.add('active'); setTimeout(() => { loginModalContent.classList.remove('scale-95', 'opacity-0'); }, 50); });
            const closeLoginModal = () => { loginModalContent.classList.add('scale-95', 'opacity-0'); setTimeout(() => { loginModal.classList.remove('active'); }, 200); };
            closeLoginBtn.addEventListener('click', closeLoginModal);
            loginModal.addEventListener('click', (e) => { if (e.target === loginModal) closeLoginModal(); });
            loginForm.addEventListener('submit', (e) => { e.preventDefault(); const name = document.getElementById('name').value; localStorage.setItem('isLoggedIn', 'true'); localStorage.setItem('userName', name); updateLoginUI(); closeLoginModal(); });
            profileIcon.addEventListener('click', () => { const userName = localStorage.getItem('userName'); if (confirm(`Logged in as ${userName}.\nAre you sure you want to log out?`)) { localStorage.removeItem('isLoggedIn'); localStorage.removeItem('userName'); updateLoginUI(); } });
            updateLoginUI();

            // --- INTERACTIVE QUIZ LOGIC (INTERNSHIPS/SCHOLARSHIPS) ---
            const internshipLink = document.getElementById('internshipLink');
            const scholarshipLink = document.getElementById('scholarshipLink');
            const interactiveModal = document.getElementById('interactiveModal');
            const interactiveInnerModal = document.getElementById('interactiveInnerModal');
            const interactiveModalContent = document.getElementById('interactiveModalContent');
            const closeInteractiveBtn = document.getElementById('closeInteractive');
            let currentQuizType = null; let userAnswers = {};
            const quizData = { internship: { title: "Find Your Perfect Internship", questions: [ { key: 'field', text: 'What is your field of interest?', options: [ { text: 'Engineering / Technical', value: 'engineering' }, { text: 'Medical', value: 'medical' }, { text: 'Arts / Social Work', value: 'arts' }, { text: 'Management', value: 'management' }, ] }, { key: 'educationLevel', text: 'What is your current education level?', options: [ { text: '12th Pass', value: '12th_pass' }, { text: 'Undergraduate Student', value: 'undergraduate' }, { text: 'Graduate / Post-Graduate', value: 'graduate' }, ] } ] }, scholarship: { title: "Find a Scholarship for You", questions: [ { key: 'eligibilityLevel', text: 'What is your current class/stage?', options: [ { text: 'After 10th (Class 11/12)', value: 'post10th' }, { text: 'After 12th (Undergraduate)', value: 'post12th' }, ] }, { key: 'category', text: 'Which category do you belong to?', options: [ { text: 'General', value: 'general' }, { text: 'SC / ST', value: 'sc_st' }, { text: 'OBC', value: 'obc' }, { text: 'EWS', value: 'ews' }, { text: 'Girls Student', value: 'girls' }, ] } ] } };
            function startInteractiveQuiz(type) { currentQuizType = type; userAnswers = {}; renderInteractiveStep(0); interactiveModal.classList.add('active'); setTimeout(() => interactiveInnerModal.classList.remove('scale-95', 'opacity-0'), 50); }
            function renderInteractiveStep(stepIndex) { const data = quizData[currentQuizType]; if (stepIndex >= data.questions.length) { showInteractiveResults(); return; } const question = data.questions[stepIndex]; let optionsHTML = question.options.map(opt => `<button class="interactive-option w-full text-left p-4 border-2 border-gray-200 rounded-lg hover:border-purple-500 hover:bg-purple-50" data-key="${question.key}" data-value="${opt.value}">${opt.text}</button>`).join(''); interactiveModalContent.innerHTML = `<h2 class="text-2xl font-bold text-center mb-2">${data.title}</h2><p class="text-gray-600 text-center mb-6">Step ${stepIndex + 1} of ${data.questions.length}</p><h3 class="text-xl font-semibold mb-6 text-center">${question.text}</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">${optionsHTML}</div><div class="flex justify-between"><button id="backBtn" class="bg-gray-200 text-gray-800 px-6 py-2 rounded-full font-semibold hover:bg-gray-300 ${stepIndex === 0 ? 'invisible' : ''}">Back</button><button id="nextBtn" class="bg-purple-600 text-white px-6 py-2 rounded-full font-semibold hover:bg-purple-700 invisible">Next</button></div>`; const optionButtons = interactiveModalContent.querySelectorAll('.interactive-option'); optionButtons.forEach(btn => { btn.addEventListener('click', () => { userAnswers[btn.dataset.key] = btn.dataset.value; optionButtons.forEach(b => b.classList.remove('selected')); btn.classList.add('selected'); document.getElementById('nextBtn').classList.remove('invisible'); }); }); document.getElementById('nextBtn').addEventListener('click', () => renderInteractiveStep(stepIndex + 1)); if(stepIndex > 0) document.getElementById('backBtn').addEventListener('click', () => renderInteractiveStep(stepIndex - 1)); }
            function showInteractiveResults() { let results = []; if (currentQuizType === 'internship') { results = internshipsData.filter(item => item.fields.includes(userAnswers.field) && item.educationLevel.includes(userAnswers.educationLevel)); } else if (currentQuizType === 'scholarship') { results = scholarshipsData.filter(item => item.eligibilityLevel.includes(userAnswers.eligibilityLevel) && item.category.includes(userAnswers.category)); } let resultsHTML = ''; if (results.length > 0) { resultsHTML = results.map(item => `<div class="bg-gray-100 p-6 rounded-lg mb-4"><h4 class="font-bold text-lg text-purple-800">${item.title}</h4><p class="text-sm text-gray-500 mb-2">${item.provider}</p><p class="text-gray-700 mb-4">${item.description}</p><a href="${item.link}" target="_blank" class="inline-block bg-green-500 text-white px-5 py-2 rounded-full font-semibold hover:bg-green-600 transition">Apply Now &rarr;</a></div>`).join(''); } else { resultsHTML = `<p class="text-center text-gray-600 py-8">Sorry, no matching opportunities found based on your selections. Please try again with different criteria.</p>`; } interactiveModalContent.innerHTML = `<h2 class="text-2xl font-bold text-center mb-6">Here are your personalized results:</h2><div class="max-h-96 overflow-y-auto pr-2">${resultsHTML}</div><div class="text-center mt-6"><button id="restartInteractive" class="bg-purple-600 text-white px-8 py-3 rounded-full font-semibold hover:bg-purple-700">Start Over</button></div>`; document.getElementById('restartInteractive').addEventListener('click', () => startInteractiveQuiz(currentQuizType)); }
            internshipLink.addEventListener('click', (e) => { e.preventDefault(); startInteractiveQuiz('internship'); }); scholarshipLink.addEventListener('click', (e) => { e.preventDefault(); startInteractiveQuiz('scholarship'); });
            const closeInteractiveModal = () => { interactiveInnerModal.classList.add('scale-95', 'opacity-0'); setTimeout(() => interactiveModal.classList.remove('active'), 200); };
            closeInteractiveBtn.addEventListener('click', closeInteractiveModal); interactiveModal.addEventListener('click', (e) => { if (e.target === interactiveModal) closeInteractiveModal(); });

            // --- ALL OTHER PAGE LOGIC ---
            const observer = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('visible'); }); }, { threshold: 0.1 });
            const elementsToAnimate = document.querySelectorAll('.fade-in-up');
            elementsToAnimate.forEach(el => observer.observe(el));
            const quizContainer = document.getElementById('quiz-container'), quizResult = document.getElementById('quiz-result'), quizOptions = document.querySelectorAll('.quiz-option'), quizSteps = document.querySelectorAll('.quiz-step'), progressBar = document.getElementById('quiz-progress'), retakeQuizBtn = document.getElementById('retake-quiz');
            let currentStep = 1; const totalSteps = 5; let scores = { Science: 0, Arts: 0, Commerce: 0, Vocational: 0 };
            const streamInfo = { Science: { description: "You seem to have a knack for analytical thinking and problem-solving. The science stream opens doors to careers in technology, medicine, and research.", subjects: "Physics, Chemistry, Math, Biology, Computer Science" }, Arts: { description: "You appear to be creative, expressive, and interested in understanding human society. The arts stream can lead to fulfilling careers in civil services, teaching, journalism, and more.", subjects: "History, Political Science, Sociology, English Literature, Psychology" }, Commerce: { description: "You show an aptitude for numbers, business, and financial systems. The commerce stream is your gateway to becoming a CA, financial analyst, or a business leader.", subjects: "Accountancy, Business Studies, Economics, Mathematics" }, Vocational: { description: "You have a practical, hands-on approach to learning. Vocational courses offer direct entry into skilled professions in IT, design, and technical fields.", subjects: "Information Technology, Web Design, Tourism, Banking" } };
            quizOptions.forEach(button => { button.addEventListener('click', () => { const stream = button.dataset.stream; scores[stream]++; setTimeout(() => { if (currentStep < totalSteps) { quizSteps[currentStep - 1].classList.remove('active'); currentStep++; quizSteps[currentStep - 1].classList.add('active'); updateProgressBar(); } else { showResults(); } }, 200); }); });
            function updateProgressBar() { const progress = ((currentStep - 1) / totalSteps) * 100; progressBar.style.width = `${progress}%`; }
            function showResults() {
                quizContainer.classList.add('hidden');
                const winner = Object.keys(scores).reduce((a, b) => scores[a] > scores[b] ? a : b);
                document.getElementById('result-stream').innerText = winner;
                document.getElementById('result-description').innerText = streamInfo[winner].description;
                
                const subjectsContainer = document.getElementById('result-subjects');
                subjectsContainer.innerHTML = ''; // Clear previous results
                const subjects = streamInfo[winner].subjects.split(', ');
                const colors = ['bg-purple-100 text-purple-800', 'bg-teal-100 text-teal-800', 'bg-pink-100 text-pink-800', 'bg-indigo-100 text-indigo-800', 'bg-amber-100 text-amber-800'];
                
                subjects.forEach((subject, index) => {
                    const pill = document.createElement('span');
                    pill.className = `px-4 py-2 rounded-full font-semibold text-sm shadow-md ${colors[index % colors.length]}`;
                    pill.innerText = subject;
                    subjectsContainer.appendChild(pill);
                });

                quizResult.classList.remove('hidden');
            }
            retakeQuizBtn.addEventListener('click', () => { currentStep = 1; scores = { Science: 0, Arts: 0, Commerce: 0, Vocational: 0 }; quizResult.classList.add('hidden'); quizSteps.forEach(step => step.classList.remove('active')); quizSteps[0].classList.add('active'); quizContainer.classList.remove('hidden'); progressBar.style.width = `0%`; });
            const courseCards = document.querySelectorAll('.course-card'), courseModal = document.getElementById('courseModal'), closeCourse = document.getElementById('closeCourse'), courseModalContent = document.getElementById('courseModalContent'), courseInnerModal = document.getElementById('courseInnerModal');
            const courseDetails = { ba: { title: 'Bachelor of Arts (B.A.)' }, bsc: { title: 'Bachelor of Science (B.Sc.)' }, bcom: { title: 'Bachelor of Commerce (B.Com.)' } };
            courseCards.forEach(card => { card.addEventListener('click', () => { const course = card.dataset.course; courseModalContent.innerHTML = `<h2 class="text-3xl font-bold mb-4 text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 to-blue-600">${courseDetails[course].title}</h2><h3 class="text-xl font-bold mb-4">Career Paths</h3><ul class="list-disc list-inside text-gray-600 space-y-2">${course === 'ba' ? `<li><b>Civil Services (IAS/KAS):</b> Requires strong understanding of humanities.</li><li><b>Journalism & Mass Communication:</b> Excellent writing and communication skills.</li><li><b>Teaching:</b> B.Ed. after B.A. is a popular choice.</li><li><b>Law (L.L.B.):</b> Pursue a 3-year L.L.B. degree after graduation.</li><li><b>Higher Education:</b> M.A., PhD in various subjects like History, English, Sociology.</li>` : ''}${course === 'bsc' ? `<li><b>Scientific Research:</b> Join research institutions like ISRO, DRDO.</li><li><b>Healthcare:</b> Path to medicine, pharmacy, or allied health services.</li><li><b>Information Technology:</b> Roles like Software Developer, Data Analyst.</li><li><b>Environmental Science:</b> Work as a conservationist or environmental consultant.</li><li><b>Higher Education:</b> M.Sc., M.Tech, MCA, PhD.</li>` : ''}${course === 'bcom' ? `<li><b>Chartered Accountancy (CA):</b> A prestigious professional qualification.</li><li><b>Banking & Finance:</b> Roles in private and public sector banks.</li><li><b>Management (MBA):</b> A B.Com degree is a strong foundation for an MBA.</li><li><b>Entrepreneurship:</b> Start and manage your own business.</li><li><b>Company Secretary (CS):</b> Corporate governance and legal compliance roles.</li>` : ''}</ul>`; courseModal.classList.add('active'); setTimeout(() => courseInnerModal.classList.remove('scale-95', 'opacity-0'), 50); }); });
            const closeCourseModal = () => { courseInnerModal.classList.add('scale-95', 'opacity-0'); setTimeout(() => courseModal.classList.remove('active'), 200); };
            closeCourse.addEventListener('click', closeCourseModal); courseModal.addEventListener('click', (e) => { if(e.target === courseModal) closeCourseModal(); });
            const collegeList = document.getElementById('college-list'), collegeSearch = document.getElementById('college-search'), districtFilter = document.getElementById('district-filter'), collegeModal = document.getElementById('collegeModal'), closeCollege = document.getElementById('closeCollege'), collegeModalContent = document.getElementById('collegeModalContent'), collegeInnerModal = document.getElementById('collegeInnerModal');
            const colleges = [{ name: 'Amar Singh College', district: 'Srinagar', courses: ['B.A.', 'B.Sc.', 'B.Com.'], facilities: ['Hostel', 'Library', 'Wi-Fi'] }, { name: 'Govt. Gandhi Memorial Science College', district: 'Jammu', courses: ['B.Sc.', 'BCA'], facilities: ['Lab', 'Library', 'Internet'] }, { name: 'Govt. Degree College for Women, Anantnag', district: 'Anantnag', courses: ['B.A.', 'B.Sc.'], facilities: ['Library', 'Canteen'] }, { name: 'Govt. Degree College, Baramulla', district: 'Baramulla', courses: ['B.A.', 'B.Sc.', 'B.Com.', 'BBA'], facilities: ['Hostel', 'Lab', 'Library'] }, { name: 'SP College, Srinagar', district: 'Srinagar', courses: ['B.Sc. (Medical)', 'B.Sc. (Non-Medical)', 'BCA'], facilities: ['Advanced Labs', 'Library', 'Internet'] }, { name: 'Govt. College for Women, Parade Ground', district: 'Jammu', courses: ['B.A.', 'B.Sc.', 'B.Com.', 'Home Science'], facilities: ['Hostel', 'Library', 'Sports Complex'] }];
            function renderColleges(filteredColleges) { collegeList.innerHTML = ''; filteredColleges.forEach((college, index) => { const card = document.createElement('div'); card.className = 'bg-white p-6 rounded-xl shadow-md hover:shadow-xl transition-all transform hover:-translate-y-1 cursor-pointer fade-in-up'; card.style.transitionDelay = `${index * 50}ms`; card.innerHTML = `<h3 class="text-xl font-bold text-gray-900">${college.name}</h3><p class="text-purple-600 font-semibold">${college.district}</p><div class="mt-4 flex flex-wrap gap-2">${college.courses.map(course => `<span class="bg-gray-200 text-gray-700 text-xs font-semibold px-2.5 py-1 rounded-full">${course}</span>`).join('')}</div>`; card.addEventListener('click', () => showCollegeDetails(college)); collegeList.appendChild(card); }); collegeList.querySelectorAll('.fade-in-up').forEach(el => observer.observe(el)); }
            function filterColleges() { const searchTerm = collegeSearch.value.toLowerCase(); const selectedDistrict = districtFilter.value; const filtered = colleges.filter(college => { const nameMatch = college.name.toLowerCase().includes(searchTerm); const districtMatch = selectedDistrict ? college.district === selectedDistrict : true; return nameMatch && districtMatch; }); renderColleges(filtered); }
            function showCollegeDetails(college){ collegeModalContent.innerHTML = `<h2 class="text-3xl font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-indigo-600">${college.name}</h2><p class="text-gray-500 text-lg mb-4">${college.district}</p><h3 class="text-xl font-semibold mt-6 mb-2">Courses Offered:</h3><p class="text-gray-700">${college.courses.join(', ')}</p><h3 class="text-xl font-semibold mt-6 mb-2">Facilities:</h3><p class="text-gray-700">${college.facilities.join(', ')}</p><p class="mt-6 text-sm text-gray-500">Note: Please visit the official college website for the latest cut-off and eligibility criteria.</p>`; collegeModal.classList.add('active'); setTimeout(() => collegeInnerModal.classList.remove('scale-95', 'opacity-0'), 50); }
            const closeCollegeModal = () => { collegeInnerModal.classList.add('scale-95', 'opacity-0'); setTimeout(() => collegeModal.classList.remove('active'), 200); };
            collegeSearch.addEventListener('input', filterColleges); districtFilter.addEventListener('change', filterColleges); closeCollege.addEventListener('click', closeCollegeModal); collegeModal.addEventListener('click', (e) => { if(e.target === collegeModal) closeCollegeModal(); });
            renderColleges(colleges);
        });